### ISSUE TITLE
run.sh not present

### ISSUE THREAD

**Issue by squidvisa** [smac89/java-cef-build#1]
unzip linux64.zip

java-cef-build-jars/readme/README.txt refers to "run.sh" and MainWindow sample application, but
does not appear to be present.

$ find . -name run.sh | wc -l
0

**Comment by smac89** [comment]
This is true. The packaging process currently discards the test stuff. Since it looks like people may actually want to run the tests locally, I will update the builds to also produce the test artifacts

**Comment by smac89** [comment]
Fixed in latest release. All files are now uploaded.
The docs are located [here](https://github.com/smac89/java-cef-build/tree/gh-pages)

**Comment by squidvisa** [comment]
Thanks so much, I'm very grateful!

Steve
